apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: aws-amazon-linux-ami
spec:
  forProvider:
    module: |
      # Get latest AMI ID for Amazon Linux2 OS
      data "aws_ami" "amzlinux2" {
        most_recent = true
        owners = [ "amazon" ]
        filter {
          name = "name"
          values = [ "amzn2-ami-hvm-*-gp2" ]
        }
        filter {
          name = "root-device-type"
          values = [ "ebs" ]
        }
        filter {
          name = "virtualization-type"
          values = [ "hvm" ]
        }
        filter {
          name = "architecture"
          values = [ "x86_64" ]
        }
       }
       output "amzlinux2id" {
         value = data.aws_ami.amzlinux2.id
       } 
    source: Inline
  providerConfigRef:
    name: tf-aws
