apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argo-cd
    targetRevision: 7.8.11
  - repoURL: git@github.com:jcdematos/argocd-lab.git
    targetRevision: develop
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
