apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boostrap
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: boostrap
    repoURL: git@github.com:jcdematos/argocd-lab.git
    targetRevision: develop
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
