apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  sources:
  - repoURL: 'https://istio-release.storage.googleapis.com/charts'
    chart: istiod
    targetRevision: 1.25.0
  - repoURL: git@github.com:jcdematos/istiod.git
    targetRevision: develop
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
